// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Dua3tW9yn6JqSvyWiLIb93Uvq2hRH_U',
    appId: '1:23126690932:web:671378b3fdcd6e2b921521',
    messagingSenderId: '23126690932',
    projectId: 'college-app-275ae',
    authDomain: 'college-app-275ae.firebaseapp.com',
    storageBucket: 'college-app-275ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqkq9XlmiJztipSRHFwuJNEXTOkLyIDn4',
    appId: '1:23126690932:android:e19c0df044a045cb921521',
    messagingSenderId: '23126690932',
    projectId: 'college-app-275ae',
    storageBucket: 'college-app-275ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2IQWk30d7xctLwkHdUSTLQ0O6HWqJmYI',
    appId: '1:23126690932:ios:89b3f63e1d4c7ad2921521',
    messagingSenderId: '23126690932',
    projectId: 'college-app-275ae',
    storageBucket: 'college-app-275ae.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2IQWk30d7xctLwkHdUSTLQ0O6HWqJmYI',
    appId: '1:23126690932:ios:89b3f63e1d4c7ad2921521',
    messagingSenderId: '23126690932',
    projectId: 'college-app-275ae',
    storageBucket: 'college-app-275ae.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Dua3tW9yn6JqSvyWiLIb93Uvq2hRH_U',
    appId: '1:23126690932:web:c8aeb52845be0fe6921521',
    messagingSenderId: '23126690932',
    projectId: 'college-app-275ae',
    authDomain: 'college-app-275ae.firebaseapp.com',
    storageBucket: 'college-app-275ae.firebasestorage.app',
  );
}
